# Generated by Django 3.2.3 on 2021-05-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiante', '0002_auto_20210530_1138'),
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.docente')),
                ('estudiantes', models.ManyToManyField(to='Estudiante.Estudiante')),
            ],
        ),
    ]
