# Generated by Django 2.2.22 on 2021-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
