# Generated by Django 2.2 on 2021-05-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('colegio', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('grupo', models.CharField(max_length=50, null=True)),
                ('grado', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
