# Generated by Django 3.1.7 on 2021-03-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colegio', '0001_initial'),
        ('Acudiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('acudiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Acudiente.acudiente')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.colegio')),
            ],
        ),
    ]
