# Generated by Django 3.2.3 on 2021-05-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colegio', '0001_initial'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Colegio.colegio'),
            preserve_default=False,
        ),
    ]
