# Generated by Django 3.1.7 on 2021-03-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='acudiente',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
