# Generated by Django 3.1.7 on 2021-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0003_auto_20210331_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
