# Generated by Django 3.1.7 on 2021-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0004_estudiante_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
