# Generated by Django 3.1.7 on 2021-05-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grupo', '0001_initial'),
        ('Grado', '0001_initial'),
        ('Estudiante', '0005_auto_20210401_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grado.grado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grupo.grupo'),
        ),
    ]
