# Generated by Django 2.2 on 2021-05-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10, null=True)),
                ('estudiante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiante.Estudiante')),
            ],
        ),
    ]
