# Generated by Django 3.1.7 on 2021-03-31 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0002_auto_20210331_0203'),
        ('Acudiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='estudiante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estudiante.estudiante'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
