# Generated by Django 3.1.7 on 2021-03-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acudiente', '0002_auto_20210331_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
