# Generated by Django 3.1.7 on 2021-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acudiente', '0003_acudiente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acudiente',
            name='id',
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
