# Generated by Django 2.2.22 on 2021-05-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=255)),
                ('estudianteEmail', models.CharField(default=None, max_length=255)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Factura.Factura')),
            ],
        ),
    ]
