# Generated by Django 2.2.22 on 2021-05-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='factura',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Factura.Factura'),
        ),
    ]
