# Generated by Django 3.2.3 on 2021-05-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colegio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.colegio')),
            ],
        ),
    ]
